### PR TITLE
New stuff

### LINKED ISSUE #16: Use coala-json to get bear list
Blocked by https://github.com/coala-analyzer/coala/pull/2337

### PR DESCRIPTION
**Pull request by arafsheikh**
Fixes #16

### CODE REVIEW

**Comment by arafsheikh** [comment]
@harshdattani Travis times out while downloading stuff from the eclipse website for some reason. But the tests once passed for these commits here https://travis-ci.org/coala-analyzer/coala-eclipse/builds/144208058.

**Comment by sils1297** [comment]
@arafsheikh can you increase the timeout?

**Comment by arafsheikh** [comment]
@harshdattani The PR is ready. Please review.

**Comment by harshdattani** [comment]
ack ae8d98e

**Comment by harshdattani** [comment]
ack	3abe286

**Comment by harshdattani** [comment]
ack	555e68f

**Comment by harshdattani** [comment]
ack 0238e7d

**Comment by harshdattani** [comment]
ack f4283ec

**Comment by harshdattani** [comment]
ack 2b90dcc

**Pull request merged**
