### PR TITLE
Add .coafile and refactor accordingly

### PR DESCRIPTION
**Pull request by arafsheikh**

### CODE REVIEW

**Comment by harshdattani** [comment]
Looks Good to me

**Comment by sils1297** [comment]
@harshdattani we do commit based review, so you would ideally look at each commit individually and acknowledge it. You can acknowledge with a comment that has `ack` or `unack` at the start or end and the commit SHA somewhere in it

**Comment by harshdattani** [comment]
ack b9119a4

**Comment by harshdattani** [comment]
ack b74a29d

**Comment by harshdattani** [comment]
ack 1699842

**Pull request merged**
